import type { AgentsMdSummary, AreaSummary, RiskyNode } from './types.js';

export const START_MARKER = '<!-- glassbox:start -->';
export const END_MARKER = '<!-- glassbox:end -->';
export const DEFAULT_MAX_LINES = 60;
export const MORE_HINT = 'query with glassbox where';

/** Prefix of the timestamp line; ignored when checking whether the block changed. */
export const STAMP_PREFIX = '_Generated by glassbox';

const MAX_ENTRY_POINTS = 3;
const MAX_TAGS = 30;
const MAX_TEXT = 100;

const USAGE: readonly string[] = [
  '### How to query',
  'MCP tools (same in Claude Code and Codex), with CLI equivalents:',
  '- `ask`: typed question over a path, diff or nodes. CLI: `glassbox ask "<question>" <path>`',
  '- `where`: rank nodes likely to hold a concept. CLI: `glassbox where "<concept>"`',
  '- `triage`: risk of a diff per chunk, plus graph impact. CLI: `glassbox triage`',
  '- `decide`: answer an "A or B?" question with probabilities. CLI: `glassbox decide "<question>"`',
  '- `explain`: evidence and why for an earlier decision. CLI: `glassbox explain <id>`',
  '- `graph`: a node\'s neighbours and stored tags. MCP only.',
  '- `refresh`: re-index changed files. CLI: `glassbox index`',
];

export interface RenderedBlock {
  /** Block lines, markers included, joined with '\n'. */
  text: string;
  lines: number;
  truncated: boolean;
}

/** Single line, no HTML comments (they could fake a marker), bounded length. */
function clean(text: string, max = MAX_TEXT): string {
  const flat = text.replace(/<!--|-->/g, '').replace(/\s+/g, ' ').trim();
  return flat.length > max ? `${flat.slice(0, max - 3)}...` : flat;
}

function more(n: number): string {
  return `(+${n} more, ${MORE_HINT})`;
}

function areaLine(a: AreaSummary): string {
  const shown = a.entryPoints.slice(0, MAX_ENTRY_POINTS).map((e) => `\`${clean(e)}\``);
  const extra = a.entryPoints.length - shown.length;
  if (extra > 0) shown.push(`+${extra} more`);
  const entries = shown.length > 0 ? `: ${shown.join(', ')}` : '';
  return `- **${clean(a.name, 60)}** (${a.nodeCount} nodes)${entries}`;
}

function riskyLine(n: RiskyNode): string {
  const p = Math.min(1, Math.max(0, n.p)).toFixed(2);
  const reason = clean(n.reason);
  return `- \`${clean(n.name, 60)}\` ${clean(n.file)}:${n.line} p=${p}${reason ? `: ${reason}` : ''}`;
}

function listSection(title: string, items: string[], limit: number, empty: string): string[] {
  const out = [title];
  if (items.length === 0) return [...out, empty];
  const shown = items.slice(0, limit);
  out.push(...shown);
  if (items.length > shown.length) out.push(`- ${more(items.length - shown.length)}`);
  return out;
}

function uniqueTags(tags: string[]): string[] {
  return [...new Set(tags.map((t) => clean(t, 40)).filter((t) => t.length > 0))].sort();
}

function tagsSection(tags: string[]): string[] {
  const uniq = uniqueTags(tags);
  if (uniq.length === 0) return ['### Tags', 'none yet (run `glassbox index`)'];
  const shown = uniq.slice(0, MAX_TAGS).map((t) => `\`${t}\``);
  const extra = uniq.length - MAX_TAGS;
  return ['### Tags', shown.join(', ') + (extra > 0 ? ` ${more(extra)}` : '')];
}

function assemble(s: AgentsMdSummary, areaLimit: number, riskyLimit: number): string[] {
  // Riskiest first; ties by location so output is stable.
  const risky = [...s.riskyNodes]
    .sort((a, b) => b.p - a.p || a.file.localeCompare(b.file) || a.line - b.line)
    .map(riskyLine);
  const areas = [...s.areas]
    .sort((a, b) => b.nodeCount - a.nodeCount || a.name.localeCompare(b.name))
    .map(areaLine);
  return [
    START_MARKER,
    '## glassbox code map',
    '',
    `${STAMP_PREFIX} at ${clean(s.generatedAt, 40)}. This block is generated: do not edit it, run \`glassbox sync-md\` to refresh._`,
    '',
    ...listSection('### Areas', areas, areaLimit, 'none yet (run `glassbox index`)'),
    '',
    ...listSection('### Risky nodes', risky, riskyLimit, 'none flagged'),
    '',
    ...tagsSection(s.availableTags),
    '',
    ...USAGE,
    END_MARKER,
  ];
}

/** Renders the managed block, cutting areas and risky nodes until it fits maxLines. */
export function renderBlock(summary: AgentsMdSummary, maxLines = DEFAULT_MAX_LINES): RenderedBlock {
  let areaLimit = summary.areas.length;
  let riskyLimit = summary.riskyNodes.length;
  let lines = assemble(summary, areaLimit, riskyLimit);
  // Shrink the longer list first; each cut adds a "+N more" line, handled by re-rendering.
  while (lines.length > maxLines && (areaLimit > 0 || riskyLimit > 0)) {
    if (riskyLimit >= areaLimit && riskyLimit > 0) riskyLimit--;
    else areaLimit--;
    lines = assemble(summary, areaLimit, riskyLimit);
  }
  const tagsCut = uniqueTags(summary.availableTags).length > MAX_TAGS;
  const truncated =
    areaLimit < summary.areas.length || riskyLimit < summary.riskyNodes.length || tagsCut;
  return { text: lines.join('\n'), lines: lines.length, truncated };
}

/** Block text without the timestamp line, for change detection. */
export function withoutStamp(block: string): string {
  return block
    .split(/\r?\n/)
    .filter((l) => !l.startsWith(STAMP_PREFIX))
    .join('\n');
}
